### ISSUE TITLE
Refact: 코드 리팩토링 하기

### ISSUE THREAD

**Issue by todoni** [todoni/slack-utils#9]
## Idea
1. http 요청 하는 부분 모듈로 분리할 수 있을 것 같다
2. 이벤트 종류가 많아지더라도 확장성 있게 코드 짤 수 있게 재구조화 해야함 (ex. dict로 관리한다든지.. if elif는 좀 ㅜ )
3. 좀 더 범용적으로... 지금은 딱 버튼클릭 했을 때! 저 모달! 만 쓸 수 있는거니까.. 잘 생각해서 짜보자
## Todo
 - [ ] channel 이름 하드코딩 하지말고 변수화
 - [x] http 요청 모듈 분리
 - [ ] lambda_handler에는 딱 lambda_handler만 있게 하고 그 이외 함수들은 좀 더 범용성 있게 추상화 시켜서 모듈 import 하는식으로 쓰자
 
흠 이러면 내가 만든 slack client와 lambda용 client가 또 생기는 느낌인데. . 어떻게 할지 고민 해봐야 할듯
